### ISSUE TITLE
Repository violates copyright

### ISSUE THREAD

**Issue by achlipala** [peteboothroyd/MIT#1]
Can you please delete this repository?  It is publicly accessible, and students can use it to cheat in 6.009.  Thanks!

**Comment by peteboothroyd** [comment]
Done. I'll close this now.

**Comment by achlipala** [comment]
Thanks, but all your code is still there in the history of this repository.  We're getting into advanced Git magic to expunge the history without just deleting the repository, but I hope you can do something that keeps the code from continuing to be freely available.
